global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'microshop-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:50051']
    metrics_path: '/metrics'

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:50052']
    metrics_path: '/metrics'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'

  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
